#! /bin/sh

bspc monitor eDP-1 -d chat term ww archiver code media
#bspc monitor HDMI-1 -d chat term ww archiver code media
"$HOME"/.config/polybar/launch.sh &
#desktop_theme_from_image next &
sxhkd &

# -------------------------------------------------------
#	bspwm config
# -------------------------------------------------------
bspc config border_width          0
bspc config window_gap            5
bspc config pointer_follows_fucus false
bspc config bottom_padding 	  32
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config fucus_by_distance	  true
bspc config focus_follows_pointer true


#----------------------------------------------------
# Border Colors
#----------------------------------------------------

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_border_color "$color1"


bspc config focused_border_color	"#000000d"
bspc config focused_locked_border_color "#dc322f"
bspc config active_border_color		"#F5F6F7"
bspc config active_locked_border_color	"#d33682"
bspc config normal_border_color		"#222222"
bspc config normal_locked_border_color	"#3F3E3B"
bspc config presel_border_color		"#000000d"
bspc config urgent_border_color		"#93a1a1"



#----------------------------------------------------
# Rules
#----------------------------------------------------

bspc rule -a Firefox  desktop=^3
bspc rule -a Thunar   desktop=^4
bspc rule -a TelegramDesktop desktop=^1
bspc rule -a Galculator  state=floating
